name: CI

on: [push]

jobs:
  test:
    name: Test on ubuntu-latest with Nim ${{ matrix.nim_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim_version: ["1.0.0", "1.0.2", "1.0.4", "stable"]
    
    steps:
    - name: Checkout euwren
      uses: actions/checkout@v1

    - name: Cache ~/.choosenim
      id: cacheChoosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim_version }}
    - name: Cache ~/.nimble
      id: cacheNimble
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim_version }}

    - name: Setup Nim environment
      uses: jiro4989/setup-nim-action@v1.0.1
      with:
        nim-version: ${{ matrix.nim_version }}
      if: >
        steps.cacheChoosenim.outputs.cache-hit != true &&
        steps.cacheNimble.outputs.cache-hit != true

    - name: Run all tests
      run: |
        nimble -y install
        nim c -r tests/teuwren
